# Haskell Stack configuration
#
# See https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-7.16

packages:
    - ./modules/lib
    - ./modules/app

nix:
    enable: true
    pure: true
    packages: []
    shell-file: modules/stack/stack.nix

flags: {}
extra-package-dbs: []
